### ISSUE TITLE
Case sensitivity issue with nsdiff

### ISSUE THREAD

**Issue by gbxyz** [fanf2/nsdiff#7]
`nsdiff` seems to care about the case of the zone it's provided as its first argument:

setup:

```
$ dig AXFR arpa @b.root-servers.net > a
$ cp a b
```

this works fine (parses both files and does not generate an error):

```
$ nsdiff arpa a b
```

this generates an error:

```
$ nsdiff ArPa a b
nsdiff: loading zone ArPa. from file a
zone ArPa/IN: loaded serial 2023011700 (DNSSEC signed)
OK
nsdiff: missing SOA record
$ echo $?
2
```

any permutation of the case in the zone argument causes this error unless it exactly matches what's in the SOA record of `b`.

**Comment by fanf2** [comment]
I think you are looking for the `-c` option
